# Generated by Django 4.2.16 on 2024-09-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="music",
            old_name="username",
            new_name="user_id",
        ),
    ]
