# Generated by Django 4.2.16 on 2024-09-21 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="file_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
