# Generated by Django 4.2.16 on 2024-09-21 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_music_file_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="file_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
