# Generated by Django 4.2.16 on 2024-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_music_file_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="duration",
            field=models.IntegerField(help_text="Duration in seconds", null=True),
        ),
    ]
